"""Tests for briefing (PUSH) + feedback (POST-TASK) loop."""

import pytest

from memee.engine.briefing import briefing, generate_claudemd_section, inject_claudemd
from memee.engine.feedback import post_task_review
from memee.storage.models import (
    AntiPattern, Decision, MaturityLevel, Memory, MemoryType,
    Project, ProjectMemory,
)


@pytest.fixture
def briefing_env(session, org):
    """Environment with patterns, anti-patterns, decisions."""
    proj = Project(
        organization_id=org.id, name="TestProject",
        path="/tmp/test-project",
        stack=["Python", "FastAPI", "SQLite"],
        tags=["python", "api"],
    )
    session.add(proj)
    session.flush()

    # Canon patterns
    for title, tags in [
        ("Always use timeout on HTTP requests", ["python", "http", "reliability"]),
        ("Use Pydantic model_validate for parsing", ["python", "pydantic", "api"]),
        ("Pre-commit hooks reduce CI failures", ["python", "ci", "quality"]),
    ]:
        m = Memory(
            type=MemoryType.PATTERN.value,
            title=title, content=f"Best practice: {title}",
            tags=tags, confidence_score=0.9,
            maturity=MaturityLevel.CANON.value,
        )
        session.add(m)
        session.flush()
        pm = ProjectMemory(project_id=proj.id, memory_id=m.id)
        session.add(pm)

    # Anti-patterns
    for title, severity, tags in [
        ("Never store API keys in code", "critical", ["security", "secrets"]),
        ("Never use eval() on user input", "critical", ["python", "security"]),
        ("Avoid N+1 queries", "high", ["python", "database"]),
    ]:
        m = Memory(
            type=MemoryType.ANTI_PATTERN.value,
            title=title, content=f"Warning: {title}",
            tags=tags, confidence_score=0.85,
        )
        session.add(m)
        session.flush()
        ap = AntiPattern(
            memory_id=m.id, severity=severity,
            trigger=title, consequence="Known failure",
            alternative="See organizational practices",
        )
        session.add(ap)

    # Decision
    m = Memory(
        type=MemoryType.DECISION.value,
        title="Decision: FastAPI over Flask",
        content="Chose FastAPI for async + auto-docs",
        tags=["decision"],
    )
    session.add(m)
    session.flush()
    dec = Decision(
        memory_id=m.id, chosen="FastAPI",
        alternatives=[{"name": "Flask", "reason_rejected": "No native async"}],
    )
    session.add(dec)
    pm = ProjectMemory(project_id=proj.id, memory_id=m.id)
    session.add(pm)

    session.commit()
    return session, proj, org


class TestBriefing:

    def test_briefing_includes_patterns(self, briefing_env):
        session, proj, org = briefing_env
        result = briefing(session, "/tmp/test-project")
        assert "timeout" in result.lower()
        assert "pydantic" in result.lower()

    def test_briefing_includes_warnings(self, briefing_env):
        session, proj, org = briefing_env
        result = briefing(session, "/tmp/test-project")
        assert "CRITICAL" in result
        assert "API keys" in result or "eval" in result

    def test_briefing_includes_decisions(self, briefing_env):
        session, proj, org = briefing_env
        result = briefing(session, "/tmp/test-project")
        assert "FastAPI" in result

    def test_briefing_compact(self, briefing_env):
        session, proj, org = briefing_env
        full = briefing(session, "/tmp/test-project", compact=False)
        compact = briefing(session, "/tmp/test-project", compact=True)
        assert len(compact) < len(full)
        assert "PATTERNS:" in compact
        assert "WARNINGS:" in compact

    def test_briefing_no_project(self, briefing_env):
        """Briefing without project shows all knowledge."""
        session, proj, org = briefing_env
        result = briefing(session)
        assert len(result) > 0


class TestClaudeMdGeneration:

    def test_generates_section(self, briefing_env):
        session, proj, org = briefing_env
        section = generate_claudemd_section(session, "/tmp/test-project")
        assert "Organizational Knowledge (auto-generated by Memee)" in section
        assert "Last updated:" in section

    def test_inject_creates_file(self, briefing_env, tmp_path):
        session, proj, org = briefing_env

        # Create a temp project directory
        project_dir = tmp_path / "myproject"
        project_dir.mkdir()

        # Register it
        proj.path = str(project_dir)
        session.commit()

        result = inject_claudemd(str(project_dir), session)
        assert result["action"] == "appended"

        # Check file was created
        claude_md = project_dir / ".claude" / "CLAUDE.md"
        assert claude_md.exists()
        content = claude_md.read_text()
        assert "Organizational Knowledge" in content

    def test_inject_preserves_existing(self, briefing_env, tmp_path):
        session, proj, org = briefing_env
        project_dir = tmp_path / "myproject2"
        project_dir.mkdir()

        # Create existing CLAUDE.md
        claude_dir = project_dir / ".claude"
        claude_dir.mkdir()
        claude_md = claude_dir / "CLAUDE.md"
        claude_md.write_text("# My Project\n\nCustom instructions here.\n")

        proj.path = str(project_dir)
        session.commit()

        inject_claudemd(str(project_dir), session)

        content = claude_md.read_text()
        assert "My Project" in content  # Original preserved
        assert "Custom instructions" in content  # Original preserved
        assert "Organizational Knowledge" in content  # New section added

    def test_inject_replaces_existing_section(self, briefing_env, tmp_path):
        session, proj, org = briefing_env
        project_dir = tmp_path / "myproject3"
        project_dir.mkdir()

        proj.path = str(project_dir)
        session.commit()

        # Inject twice — should replace, not duplicate
        inject_claudemd(str(project_dir), session)
        inject_claudemd(str(project_dir), session)

        content = (project_dir / ".claude" / "CLAUDE.md").read_text()
        count = content.count("Organizational Knowledge (auto-generated by Memee)")
        assert count == 1  # Only one section, not two

    def test_inject_idempotent_with_end_marker(self, briefing_env, tmp_path):
        """Injecting twice with different timestamps leaves ONE section.

        Regression: older code found section end by "next `## ` heading",
        which could miss or duplicate when the following content used a
        different heading level. The explicit end marker makes replace
        deterministic.
        """
        import time
        session, proj, org = briefing_env
        project_dir = tmp_path / "idempotent-inject"
        project_dir.mkdir()

        proj.path = str(project_dir)
        session.commit()

        inject_claudemd(str(project_dir), session)
        # Force a different clock tick so the "Last updated: …" line changes.
        time.sleep(1.1)
        inject_claudemd(str(project_dir), session)

        content = (project_dir / ".claude" / "CLAUDE.md").read_text()
        # Exactly one section header AND one end marker.
        assert content.count(
            "Organizational Knowledge (auto-generated by Memee)"
        ) == 1
        assert content.count("<!-- /memee-section -->") == 1

    def test_inject_preserves_heading_after_section(self, briefing_env, tmp_path):
        """A user heading that follows the Memee block survives re-injection.

        Pre-fix: the old code truncated at the next `## ` heading. So a
        trailing user section "## My notes" could be consumed by the replace.
        """
        session, proj, org = briefing_env
        project_dir = tmp_path / "preserve-heading"
        project_dir.mkdir()
        claude_dir = project_dir / ".claude"
        claude_dir.mkdir()
        claude_md = claude_dir / "CLAUDE.md"

        proj.path = str(project_dir)
        session.commit()

        # First inject creates the section.
        inject_claudemd(str(project_dir), session)
        # Add a user section AFTER the Memee block.
        existing = claude_md.read_text()
        claude_md.write_text(existing + "\n\n## My notes\n\nKeep me.\n")

        # Re-inject must not swallow "## My notes".
        inject_claudemd(str(project_dir), session)
        content = claude_md.read_text()
        assert "## My notes" in content
        assert "Keep me." in content


class TestSeveritySort:

    def test_critical_ranks_before_medium(self, session, org):
        """Lexicographic DESC sort puts medium > low > high > critical.

        Explicit CASE rank must keep critical first even with a tiny limit.
        """
        from memee.engine.briefing import briefing

        # Five APs, all different severities. The briefing's internal
        # limit is max_warnings * 3; with max_warnings=2 that's 6 candidates,
        # and we seed exactly 4 so the ORDER matters: critical must come out.
        proj = Project(
            organization_id=org.id, name="SevSortProj",
            path="/tmp/sev-sort", stack=["python"], tags=["python"],
        )
        session.add(proj)
        session.flush()

        seeds = [
            ("Medium thing", "medium"),
            ("Low thing", "low"),
            ("High thing", "high"),
            ("Critical thing", "critical"),
        ]
        for title, sev in seeds:
            m = Memory(
                type=MemoryType.ANTI_PATTERN.value,
                title=title, content=title,
                tags=["python"], confidence_score=0.8,
            )
            session.add(m)
            session.flush()
            ap = AntiPattern(
                memory_id=m.id, severity=sev,
                trigger=title, consequence="known",
            )
            session.add(ap)
        session.commit()

        result = briefing(session, "/tmp/sev-sort", max_warnings=2, max_patterns=0,
                          max_decisions=0)
        # The top-severity items must be present.
        assert "Critical thing" in result, result
        assert "High thing" in result, result
        # And the lowest-severity ones must NOT displace them.
        assert "Low thing" not in result, result


class TestFeedbackLoop:

    def test_detects_pattern_usage(self, briefing_env):
        session, proj, org = briefing_env
        diff = "+    response = requests.get(url, timeout=10)\n+    import logging\n+    logger = logging.getLogger(__name__)"
        result = post_task_review(session, diff, outcome="success")
        assert result["outcome"] == "success"
        assert result["lines_scanned"] > 0

    def test_detects_violations(self, briefing_env):
        session, proj, org = briefing_env
        diff = "+    config = eval(open('config.txt').read())"
        result = post_task_review(session, diff, outcome="failure")
        assert result["warnings_violated"] > 0

    def test_empty_diff(self, briefing_env):
        session, proj, org = briefing_env
        result = post_task_review(session, "", outcome="success")
        assert result["patterns_followed"] == 0
        assert result["warnings_violated"] == 0
