"""initial schema

Revision ID: 843e414a0596
Revises: 
Create Date: 2026-04-24 11:04:54.842102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '843e414a0596'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_date', sa.DateTime(), nullable=False),
    sa.Column('total_memories', sa.Integer(), nullable=True),
    sa.Column('canon_memories', sa.Integer(), nullable=True),
    sa.Column('hypothesis_memories', sa.Integer(), nullable=True),
    sa.Column('deprecated_memories', sa.Integer(), nullable=True),
    sa.Column('avg_confidence', sa.Float(), nullable=True),
    sa.Column('cross_project_applications', sa.Integer(), nullable=True),
    sa.Column('anti_patterns_avoided', sa.Integer(), nullable=True),
    sa.Column('research_experiments_completed', sa.Integer(), nullable=True),
    sa.Column('learning_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('maturity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('validation_count', sa.Integer(), nullable=True),
    sa.Column('invalidation_count', sa.Integer(), nullable=True),
    sa.Column('application_count', sa.Integer(), nullable=True),
    sa.Column('project_count', sa.Integer(), nullable=True),
    sa.Column('validated_project_ids', sa.JSON(), nullable=True),
    sa.Column('same_project_val_counts', sa.JSON(), nullable=True),
    sa.Column('model_families_seen', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(), nullable=True),
    sa.Column('last_applied_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(), nullable=True),
    sa.Column('deprecated_reason', sa.Text(), nullable=True),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('promoted_from', sa.String(length=36), nullable=True),
    sa.Column('source_agent', sa.String(length=255), nullable=True),
    sa.Column('source_model', sa.String(length=100), nullable=True),
    sa.Column('source_session', sa.String(length=255), nullable=True),
    sa.Column('source_commit', sa.String(length=40), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('model_count', sa.Integer(), nullable=True),
    sa.Column('evidence_chain', sa.JSON(), nullable=True),
    sa.Column('merge_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('confidence_score >= 0.0 AND confidence_score <= 1.0'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_memories_confidence', 'memories', ['confidence_score'], unique=False)
    op.create_index('ix_memories_maturity', 'memories', ['maturity'], unique=False)
    op.create_index('ix_memories_type', 'memories', ['type'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('search_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('position_of_accepted', sa.Integer(), nullable=True),
    sa.Column('returned_count', sa.Integer(), nullable=False),
    sa.Column('top_memory_id', sa.String(length=36), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('accepted_memory_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_events_accepted', 'search_events', ['accepted_memory_id'], unique=False)
    op.create_index('ix_search_events_created_at', 'search_events', ['created_at'], unique=False)
    op.create_table('anti_patterns',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('trigger', sa.Text(), nullable=False),
    sa.Column('consequence', sa.Text(), nullable=False),
    sa.Column('alternative', sa.Text(), nullable=True),
    sa.Column('detection', sa.Text(), nullable=True),
    sa.Column('occurrences', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('decisions',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('chosen', sa.Text(), nullable=False),
    sa.Column('alternatives', sa.JSON(), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.Column('outcome_date', sa.DateTime(), nullable=True),
    sa.Column('reversible', sa.Boolean(), nullable=True),
    sa.Column('decision_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('memory_id')
    )
    op.create_table('memory_connections',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('memory_tags',
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.PrimaryKeyConstraint('memory_id', 'tag')
    )
    op.create_index('ix_memory_tags_tag', 'memory_tags', ['tag'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('stack', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_active', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'path', name='uq_org_path')
    )
    op.create_table('memory_validations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('validator_model', sa.String(length=100), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_memories',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('memory_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('applied', sa.Boolean(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('outcome_evidence_type', sa.String(length=20), nullable=True),
    sa.Column('outcome_evidence_ref', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'memory_id')
    )
    op.create_table('project_tags',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'tag')
    )
    op.create_index('ix_project_tags_tag', 'project_tags', ['tag'], unique=False)
    op.create_table('research_experiments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('metric_name', sa.String(length=255), nullable=False),
    sa.Column('metric_direction', sa.String(length=10), nullable=False),
    sa.Column('verify_command', sa.Text(), nullable=False),
    sa.Column('guard_command', sa.Text(), nullable=True),
    sa.Column('scope_globs', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('final_value', sa.Float(), nullable=True),
    sa.Column('best_value', sa.Float(), nullable=True),
    sa.Column('total_iterations', sa.Integer(), nullable=True),
    sa.Column('keeps', sa.Integer(), nullable=True),
    sa.Column('discards', sa.Integer(), nullable=True),
    sa.Column('crashes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_iterations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('commit_hash', sa.String(length=40), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('guard_passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['research_experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # FTS5 virtual table + sync triggers. Mirrors database.py::init_db so
    # alembic-only bootstrap (no init_db call) still yields a working search.
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts USING fts5(
            title, content, summary, tags,
            content='memories',
            content_rowid='rowid'
        )
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS memories_fts_ai
        AFTER INSERT ON memories BEGIN
            INSERT INTO memories_fts(rowid, title, content, summary, tags)
            VALUES (new.rowid, new.title, new.content, new.summary,
                    COALESCE(new.tags, '[]'));
        END
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS memories_fts_au
        AFTER UPDATE ON memories BEGIN
            INSERT INTO memories_fts(
                memories_fts, rowid, title, content, summary, tags
            )
            VALUES ('delete', old.rowid, old.title, old.content,
                    old.summary, COALESCE(old.tags, '[]'));
            INSERT INTO memories_fts(rowid, title, content, summary, tags)
            VALUES (new.rowid, new.title, new.content, new.summary,
                    COALESCE(new.tags, '[]'));
        END
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS memories_fts_ad
        AFTER DELETE ON memories BEGIN
            INSERT INTO memories_fts(
                memories_fts, rowid, title, content, summary, tags
            )
            VALUES ('delete', old.rowid, old.title, old.content,
                    old.summary, COALESCE(old.tags, '[]'));
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # Drop FTS5 triggers + virtual table first (reverse of upgrade).
    op.execute("DROP TRIGGER IF EXISTS memories_fts_ad")
    op.execute("DROP TRIGGER IF EXISTS memories_fts_au")
    op.execute("DROP TRIGGER IF EXISTS memories_fts_ai")
    op.execute("DROP TABLE IF EXISTS memories_fts")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_iterations')
    op.drop_table('research_experiments')
    op.drop_index('ix_project_tags_tag', table_name='project_tags')
    op.drop_table('project_tags')
    op.drop_table('project_memories')
    op.drop_table('memory_validations')
    op.drop_table('projects')
    op.drop_index('ix_memory_tags_tag', table_name='memory_tags')
    op.drop_table('memory_tags')
    op.drop_table('memory_connections')
    op.drop_table('decisions')
    op.drop_table('anti_patterns')
    op.drop_index('ix_search_events_created_at', table_name='search_events')
    op.drop_index('ix_search_events_accepted', table_name='search_events')
    op.drop_table('search_events')
    op.drop_table('organizations')
    op.drop_index('ix_memories_type', table_name='memories')
    op.drop_index('ix_memories_maturity', table_name='memories')
    op.drop_index('ix_memories_confidence', table_name='memories')
    op.drop_table('memories')
    op.drop_table('learning_snapshots')
    # ### end Alembic commands ###
